CREATE DATABASE WEB;

CREATE TABLE IF NOT EXISTS USER (
    ID SERIAL,
    USERNAME VARCHAR(20),
    PASSWORD VARCHAR(20),

    CONSTRAINT PK PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS PLAYERUSER (
    USER_ID INT,
    WINS INT,
    LOSSES INT,

    CONSTRAINT FK FOREIGN KEY(USER_ID) REFERENCES USER(ID)
);

INSERT INTO USER(USERNAME, PASSWORD) VALUES ();
UPDATE USER SET ID = 0 WHERE ID = SELECT(ID) FROM USER WHERE USERNAME LIKE 'ROOT';
